name: Shellcheck

on:
  push:
    paths:
      - 'scripts/install-all.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'scripts/install-all.sh'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          set -o pipefail
          shellcheck -x scripts/install-all.sh | tee shellcheck.log
          status=$?
          if grep -Eq 'SC1009|SC1046|SC1047' shellcheck.log; then
            echo 'Critical shell syntax issue detected (SC1009/SC1046/SC1047)'
            exit 1
          fi
          exit $status
